package com.sample

import javax.swing.*;
import org.kie.api.runtime.*;
import java.util.ArrayList;

global JFrame frame;

declare enum Question
    GAME("What type of games are you looking for?", ["Party Game", "Horror Game", "Wargame"]),
      PARTY_GAME("Are you playing with Geeks?", ["Yes", "No"]),
        YES_WITH_GEEKS("Rolling dice or a bluffing game?", ["Dice", "Bluffing"]),
          DICE("Are you a zombie or a giant monster?", ["Zombie", "Monster"]),
          BLUFFING("Cooperative or competitive?", ["Cooperative", "Competitive"]),
        NO_WITH_GEEKS("Do you like trivia?", ["Yes", "No"]),
          NO_TRIVIA("How about something creative", ["Sure", "Nope"]),
            CREATIVE("Working with words or pictures", ["Words", "Pictures"]),
      HORROR_GAME("What is you favorite monster?", ["Zombies", "Cthulhu",  "Classic Movie Monsters"]),
      	ZOMBI("Boards or cards?", ["Board Game", "Card Game"]),
      	  BOARD("Survival of the Fittest or Humans vs Zombies?", ["Survival of the Fittest", "Humans vs Zombies"]),
      	    HUMANS("Does anyone want to play as the zombies", ["We are all humans", "Sure!"]),
      	CTHULHU("Ever wanted to play on his side?", ["Maybe a little",  "No!"]),
      	  CTHULHU_NO("An epic investigation or a gateway game?", ["I want an epic!",  "Gateway, please!"]),
      	MONSTER("Card-based combat or a mystery?", ["I'll crash you", "I'd rather be a detective"]),
      WARGAME("For how many players?", ["2 or more", "Just me"]),
        JUST_ME("What do you prefer?", ["Historic Battles", "Modern Air Support", "Science Fiction"]),
        TWO_OR_MORE("Do you have any wargaming experience?", ["It's new to me", "Yes"]),
          WARGAMING_EXP_YES("Want to command Roman legions?", ["Yes", "No"]),
            ROMAN_LEGIONS_NO("Lead 19th Century battle lines?", ["Yes", "No"]),
              BATTLE_LINES_NO("How about World War II?", ["Yes", "No"]),
                WW2_YES("Card- or dice- driven combat?", ["roll roll roll", "shuffle shuffle"]),
                WW2_NO("Modern Warfare, then?", ["Yes, I like the immediacy", "No, I'm tired of real wars"]),
                  MODERN_WARFARE_NO("Science fiction or alternate history?", ["Alt-History", "Science Fiction"]),
                    WAR_ALT_HISTORY("Tactical miniatures or large-scale startegy?", ["Strategic", "Tactical"]),
                    WAR_SCIENCE_FICTION("Space ships or giant robots?", ["Ships!", "Mechs!"]),
          WARGAMING_EXP_NO("Are you a fan of Risk?", ["Yes", "No"]),
            RISK_FAN_NO("World history or high fantasy?", ["History", "Fantasy"]);
    text : String
    options : ArrayList
end

declare Answer
    question : Question @key
    choice : String
end

declare Result
	text: String
end

//SUPPORT RULES
rule "asker"
when
	q: Question()
then
	Object[] options = q.getOptions().toArray();
    int ans = JOptionPane.showOptionDialog(frame, q.getText(), "", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, 1);
            
    if(ans != JOptionPane.CLOSED_OPTION) {
    	Answer answer = new Answer(q, (String)options[ans]);
    	insert(answer);
    }
	
end

rule "shower"
when
	r: Result()
then
	JOptionPane.showMessageDialog(frame, r.getText());
end

 
//DECISION RULES
//Type of game
rule "init"
then
    insert(Question.GAME);
end

rule "game - party game"
when
    Answer(question == Question.GAME, choice == "Party Game")
then
   insert(Question.PARTY_GAME);
end

rule "game - horror game"
when
    Answer(question == Question.GAME, choice == "Horror Game")
then
   insert(Question.HORROR_GAME);
end

rule "game - wargame"
when
    Answer(question == Question.GAME, choice == "Wargame")
then
   insert(Question.WARGAME);
end

//I want a party game

rule "party game - with geeks"
when
    Answer(question == Question.PARTY_GAME, choice == "Yes")
then
   insert(Question.YES_WITH_GEEKS);
end

rule "party game - no with geeks"
when
    Answer(question == Question.PARTY_GAME, choice == "No")
then
   insert(Question.NO_WITH_GEEKS);
end

//PARTY game: Dice or bluffing?

rule "dice"
when
    Answer(question == Question.YES_WITH_GEEKS, choice == "Dice")
then
   insert(Question.DICE);
end

rule "bluffing"
when
    Answer(question == Question.YES_WITH_GEEKS, choice == "Bluffing")
then
   insert(Question.BLUFFING);
end

//PARTY game: Zombie or Monster?

rule "zombie"
when
    Answer(question == Question.DICE, choice == "Zombie")
then
   insert(new Result("Zombie Dice"));
end

rule "monster"
when
    Answer(question == Question.DICE, choice == "Monster")
then
  	insert(new Result("King of Tokyo"));
end

//PARTY game: Cooperative or Competitive?

rule "cooperative"
when
    Answer(question == Question.BLUFFING, choice == "Cooperative")
then
  insert(new Result("The Resistance"));
end

rule "competitive"
when
    Answer(question == Question.BLUFFING, choice == "Competitive")
then
   insert(new Result("Coup"));
end

//PARTY game: Do you like trivia?

rule "trivia - yes"
when
    Answer(question == Question.NO_WITH_GEEKS, choice == "Yes")
then
   insert(new Result("Wits & Wagers"));
end

rule "trivia - no"
when
    Answer(question == Question.NO_WITH_GEEKS, choice == "No")
then
   insert(Question.NO_TRIVIA);
end

//PARTY game: How about something creative?

rule "creative - sure"
when
    Answer(question == Question.NO_TRIVIA, choice == "Sure")
then
   insert(Question.CREATIVE);
end

rule "creative - nope"
when
    Answer(question == Question.NO_TRIVIA, choice == "Nope")
then
   insert(new Result("Hanabi"));
end

//PARTY game: Working with words or pictures?

rule "words"
when
    Answer(question == Question.CREATIVE, choice == "Words")
then
   insert(new Result("Apples to Apples"));
end

rule "pictures"
when
    Answer(question == Question.CREATIVE, choice == "Pictures")
then
   insert(new Result("Dixit"));
end

//WAR game: For how many players

rule "war game - how many players"
when
	Answer(question == Question.WARGAME, choice == "2 or more")
then
	insert(Question.TWO_OR_MORE);
end

rule "war game - just me"
when
	Answer(question == Question.WARGAME, choice == "Just me")
then
	insert(Question.JUST_ME);
end

//WAR game: Just me choice

rule "war game - historic battles"
when
    Answer(question == Question.JUST_ME, choice == "Historic Battles")
then
	insert(new Result("Field Commander Series"));
end

rule "war game - modern air support"
when
    Answer(question == Question.JUST_ME, choice == "Modern Air Support")
then
	insert(new Result("Thunderbolt: Apache Leader"));
end

rule "war game - science fiction"
when
	Answer(question == Question.JUST_ME, choice == "Science Fiction")
then
	insert(new Result("Space Infantry"));
end

//WAR game: Do you have any wargaming experience?

rule "war game - has experience"
when
    Answer(question == Question.TWO_OR_MORE, choice == "Yes")
then
	insert(Question.WARGAMING_EXP_YES);
end

rule "war game - no experience"
when
	Answer(question == Question.TWO_OR_MORE, choice == "It's new to me")
then
	insert(Question.WARGAMING_EXP_NO);
end

//WAR game: Are you a fan of risk?

rule "war game - risk fan"
when
	Answer(question == Question.WARGAMING_EXP_NO, choice == "Yes")
then
	insert(new Result("Risk: Legacy"));
end

rule "war game - not risk fan"
when
	Answer(question == Question.WARGAMING_EXP_NO, choice == "No")
then
	insert(Question.RISK_FAN_NO);
end

//WAR game: World history, or high fantasy?

rule "war game - world history"
when
	Answer(question == Question.RISK_FAN_NO, choice == "History")
then
	insert(new Result("Memoir '44"));
end

rule "war game - high fantasy"
when
	Answer(question == Question.RISK_FAN_NO, choice == "Fantasy")
then
	insert(new Result("Battles of Westeros"));
end

//WAR game: Want to command Roman legions?

rule "war game - roman fan"
when
	Answer(question == Question.WARGAMING_EXP_YES, choice == "Yes")
then
	insert(new Result("Commands & Colors: Ancients"));
end

rule "war game - roman hater"
when
	Answer(question == Question.WARGAMING_EXP_YES, choice == "No")
then
	insert(Question.ROMAN_LEGIONS_NO);
end

//WAR game: Lead 19th century battle lines?

rule "war game - 19th battle yes"
when
	Answer(question == Question.ROMAN_LEGIONS_NO, choice == "Yes")
then
	insert(new Result("1812: The Invasion of Canada"));
end

rule "war game - 19th battle no"
when
	Answer(question == Question.ROMAN_LEGIONS_NO, choice == "No")
then
	insert(Question.BATTLE_LINES_NO);
end

//WAR game: How about World War II?

rule "war game - ww2 yes"
when 
	Answer(question == Question.BATTLE_LINES_NO, choice == "Yes")
then
	insert(Question.WW2_YES);
end

rule "war game - ww2 no"
when
	Answer(question == Question.BATTLE_LINES_NO, choice == "No")
then
	insert(Question.WW2_NO);
end

//WAR game: Card or dice driven combat?

rule "war game - card"
when
	Answer(question == Question.WW2_YES, choice == "shuffle shuffle")
then
	insert(new Result("Combat Commander Series"));
end

rule "war game - dice"
when
	Answer(question == Question.WW2_YES, choice == "roll roll roll")
then
	insert(new Result("Tide of Iron"));
end

//WAR game: Modern Warfare, then?

rule "war game - mw yes"
when
	Answer(question == Question.WW2_NO, choice == "Yes, I like the immediacy")
then
	insert(new Result("Labyrinth: The War of Terror"));
end

rule "war game - mw no"
when
	Answer(question == Question.WW2_NO, choice == "No, I'm tired of real wars")
then
	insert(Question.MODERN_WARFARE_NO);
end

//WAR game: Science Fiction or alternate history?

rule "war game - scifi"
when
	Answer(question == Question.MODERN_WARFARE_NO, choice == "Science Fiction")
then
	insert(Question.WAR_SCIENCE_FICTION);
end

rule "war game - althist"
when
	Answer(question == Question.MODERN_WARFARE_NO, choice == "Alt-History")
then
	insert(Question.WAR_ALT_HISTORY);
end

//WAR game: Tactical miniatures or large-scale strategy?

rule "war game - tactical"
when
	Answer(question == Question.WAR_ALT_HISTORY, choice == "Tactical")
then
	insert(new Result("Dust Tactics"));
end

rule "war game - startegic"
when
	Answer(question == Question.WAR_ALT_HISTORY, choice == "Strategic")
then
	insert(new Result("Fortress America"));
end

//WAR game: Space ships or giant robots?

rule "war game - ships"
when
	Answer(question == Question.WAR_SCIENCE_FICTION, choice == "Ships!")
then
	insert(new Result("Battleship Galaxies"));
end

rule "war game - mechs"
when
	Answer(question == Question.WAR_SCIENCE_FICTION, choice == "Mechs!")
then
	insert(new Result("Battletech"));
end

//HORROR game: What is your favourite monster?

rule "horror game - zombies"
when
    Answer(question == Question.HORROR_GAME, choice == "Zombies")
then
   insert(Question.ZOMBI);
end

rule "horror game - cthulhu"
when
    Answer(question == Question.HORROR_GAME, choice == "Cthulhu")
then
   insert(Question.CTHULHU);
end

rule "horror game - monster"
when
    Answer(question == Question.HORROR_GAME, choice == "Classic Movie Monsters")
then
   insert(Question.MONSTER);
end

//HORROR game: Boards or cards?

rule "horror game - board"
when
    Answer(question == Question.ZOMBI, choice == "Board Game")
then
   insert(Question.BOARD);
end

rule "horror game - card"
when
    Answer(question == Question.ZOMBI, choice == "Card Game")
then
   insert(new Result("Resident Evil \n Deckbuilding Game"));
end

//HORROR game: Survival of the Fittest or Humans vs Zombies?

rule "horror game - survival"
when
    Answer(question == Question.BOARD, choice == "Survival of the Fittest")
then
   
   insert(new Result("City of Horror"));
end

rule "horror game - humans"
when
    Answer(question == Question.BOARD, choice == "Humans vs Zombies")
then
   insert(Question.HUMANS);
end

//HORROR game: Does anyone want to play as the zombies?

rule "horror game - no as the zobies"
when
    Answer(question == Question.HUMANS, choice == "We are all humans")
then  
   insert(new Result("Last Night on Earth"));
end

rule "horror game - yes as a zombies"
when
    Answer(question == Question.BOARD, choice == "Sure!")
then
   insert(new Result("Zombiecide"));
end

//HORROR game: Ever wanted to play on Cthulhu side?

rule "horror game - no"
when
    Answer(question == Question.CTHULHU, choice == "No!")
then
   insert(Question.CTHULHU_NO);
end

rule "horror game - yes"
when
    Answer(question == Question.CTHULHU, choice == "Maybe a little")
then
   insert(new Result("Mansions of Madness"));
end

//HORROR game: An epic investigation or a gateway game?

rule "horror game - epic"
when
    Answer(question == Question.CTHULHU_NO, choice == "I want an epic!")
then
   insert(new Result("Arkham Horror"));
end

rule "horror game - gateway"
when
    Answer(question == Question.CTHULHU_NO, choice == "Gateway, please!")
then
   insert(new Result("Elder Sign"));
end

//HORROR game: Card-based combat or a mystery?

rule "horror game - combat"
when
    Answer(question == Question.MONSTER, choice == "I'll crash you")
then
   insert(new Result("Nightfall"));
end

rule "horror game - mystery"
when
    Answer(question == Question.MONSTER, choice == "I'd rather be a detective")
then
   insert(new Result("Betrayal at House on the Hill"));
end